// Link-integrity test for the Toolkit hub: every tool must be present and linked.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, '..', 'index.html'), 'utf8');

const tools = [
  ['MarginMaster', 'https://awictor.github.io/margin-master/'],
  ['Runway', 'https://awictor.github.io/runway-calc/'],
  ['RateRight', 'https://awictor.github.io/rate-right/'],
  ['Payoff', 'https://awictor.github.io/payoff/'],
  ['BreakEven', 'https://awictor.github.io/breakeven/'],
  ['TipSplit', 'https://awictor.github.io/tip-split/'],
  ['LoanCalc', 'https://awictor.github.io/loan-calc/'],
  ['NestEgg', 'https://awictor.github.io/nest-egg/'],
  ['PassForge', 'https://awictor.github.io/pass-forge/'],
  ['Contrast', 'https://awictor.github.io/contrast/'],
  ['CronPal', 'https://awictor.github.io/cron-pal/'],
  ['JWTPeek', 'https://awictor.github.io/jwt-peek/'],
  ['WordCount', 'https://awictor.github.io/word-count/'],
  ['EpochConvert', 'https://awictor.github.io/epoch-convert/'],
  ['ColorConvert', 'https://awictor.github.io/color-convert/'],
  ['CaseKit', 'https://awictor.github.io/case-kit/'],
  ['EncodeKit', 'https://awictor.github.io/encode-kit/'],
  ['UUIDGen', 'https://awictor.github.io/uuid-gen/'],
  ['JSONFormat', 'https://awictor.github.io/json-format/'],
  ['DiffCheck', 'https://awictor.github.io/diff-check/'],
  ['LoremGen', 'https://awictor.github.io/lorem-gen/'],
  ['HashGen', 'https://awictor.github.io/hash-gen/'],
  ['BaseConvert', 'https://awictor.github.io/base-convert/'],
  ['AspectRatio', 'https://awictor.github.io/aspect-ratio/'],
  ['PercentCalc', 'https://awictor.github.io/percent-calc/'],
  ['CSVJSON', 'https://awictor.github.io/csv-json/'],
  ['BMICalc', 'https://awictor.github.io/bmi-calc/'],
  ['TDEECalc', 'https://awictor.github.io/tdee-calc/'],
  ['DateDiff', 'https://awictor.github.io/date-diff/'],
  ['TaxCalc', 'https://awictor.github.io/tax-calc/'],
  ['RomanNumeral', 'https://awictor.github.io/roman-numeral/'],
  ['UnitConvert', 'https://awictor.github.io/unit-convert/'],
  ['DiscountCalc', 'https://awictor.github.io/discount-calc/'],
  ['GradeCalc', 'https://awictor.github.io/grade-calc/'],
  ['PaceCalc', 'https://awictor.github.io/pace-calc/'],
  ['PxRem', 'https://awictor.github.io/px-rem/'],
  ['LineTools', 'https://awictor.github.io/line-tools/'],
  ['RandomPick', 'https://awictor.github.io/random-pick/'],
  ['RegexTest', 'https://awictor.github.io/regex-test/'],
  ['MorseCode', 'https://awictor.github.io/morse-code/'],
  ['WageCalc', 'https://awictor.github.io/wage-calc/'],
  ['URLParse', 'https://awictor.github.io/url-parse/'],
  ['TypeScale', 'https://awictor.github.io/type-scale/'],
  ['OneRepMax', 'https://awictor.github.io/one-rep-max/'],
  ['HTMLEntities', 'https://awictor.github.io/html-entities/'],
  ['StrengthCheck', 'https://awictor.github.io/strength-check/'],
  ['SaveGoal', 'https://awictor.github.io/save-goal/'],
  ['TitleCase', 'https://awictor.github.io/title-case/'],
  ['AgeCalc', 'https://awictor.github.io/age-calc/'],
  ['InflationCalc', 'https://awictor.github.io/inflation-calc/'],
  ['WaterIntake', 'https://awictor.github.io/water-intake/'],
  ['FractionConvert', 'https://awictor.github.io/fraction-convert/'],
  ['ClampGen', 'https://awictor.github.io/clamp-gen/'],
  ['Slugify', 'https://awictor.github.io/slugify/'],
  ['MacroCalc', 'https://awictor.github.io/macro-calc/'],
  ['ROICalc', 'https://awictor.github.io/roi-calc/'],
  ['SubnetCalc', 'https://awictor.github.io/subnet-calc/'],
  ['NumWords', 'https://awictor.github.io/num-words/'],
  ['HoursCalc', 'https://awictor.github.io/hours-calc/'],
  ['ShadeGen', 'https://awictor.github.io/shade-gen/'],
  ['AuthCode', 'https://awictor.github.io/auth-code/'],
  ['MdTable', 'https://awictor.github.io/md-table/'],
  ['HeartZones', 'https://awictor.github.io/heart-zones/'],
  ['CSPKit', 'https://awictor.github.io/csp-kit/'],
  ['GradientGen', 'https://awictor.github.io/gradient-gen/'],
  ['MdPreview', 'https://awictor.github.io/md-preview/'],
  ['ByteSize', 'https://awictor.github.io/byte-size/'],
  ['FindReplace', 'https://awictor.github.io/find-replace/'],
  ['HmacGen', 'https://awictor.github.io/hmac-gen/'],
  ['JsonToTs', 'https://awictor.github.io/json-to-ts/'],
  ['BodyFat', 'https://awictor.github.io/body-fat/'],
  ['MathKit', 'https://awictor.github.io/math-kit/'],
  ['ShadowGen', 'https://awictor.github.io/shadow-gen/'],
  ['TokenGen', 'https://awictor.github.io/token-gen/'],
  ['Amortize', 'https://awictor.github.io/amortize/'],
  ['Similarity', 'https://awictor.github.io/similarity/'],
  ['CheckDigit', 'https://awictor.github.io/check-digit/'],
  ['Easing', 'https://awictor.github.io/easing/'],
  ['CipherNote', 'https://awictor.github.io/cipher-note/'],
  ['Duration', 'https://awictor.github.io/duration/'],
  ['Harmony', 'https://awictor.github.io/color-harmony/'],
  ['DotEnv', 'https://awictor.github.io/dotenv/'],
  ['TextClean', 'https://awictor.github.io/text-clean/'],
  ['IdealWeight', 'https://awictor.github.io/ideal-weight/'],
  ['SriGen', 'https://awictor.github.io/sri-gen/'],
  ['RotCipher', 'https://awictor.github.io/rot-cipher/'],
  ['A1C', 'https://awictor.github.io/a1c/'],
  ['GPACalc', 'https://awictor.github.io/gpa-calc/'],
  ['FilterGen', 'https://awictor.github.io/filter-gen/'],
  ['UlidGen', 'https://awictor.github.io/ulid-gen/'],
  ['SciNotation', 'https://awictor.github.io/sci-notation/'],
  ['DueDate', 'https://awictor.github.io/due-date/'],
  ['Base32', 'https://awictor.github.io/base32/'],
  ['WordFreq', 'https://awictor.github.io/word-freq/'],
  ['Uuid5', 'https://awictor.github.io/uuid5/'],
  ['CalBurn', 'https://awictor.github.io/cal-burn/'],
  ['TextReverse', 'https://awictor.github.io/text-reverse/'],
  ['RadiusGen', 'https://awictor.github.io/radius-gen/'],
  ['JsonToCsv', 'https://awictor.github.io/json-to-csv/'],
  ['SleepCalc', 'https://awictor.github.io/sleep-calc/'],
  ['QueryString', 'https://awictor.github.io/query-string/'],
  ['Readability', 'https://awictor.github.io/readability/'],
  ['Base58', 'https://awictor.github.io/base58/'],
  ['TransformGen', 'https://awictor.github.io/transform-gen/'],
  ['WaistHeight', 'https://awictor.github.io/waist-height/'],
  ['Unicode', 'https://awictor.github.io/unicode/'],
  ['MdToc', 'https://awictor.github.io/md-toc/'],
  ['Crc32', 'https://awictor.github.io/crc32/'],
  ['TextShadowGen', 'https://awictor.github.io/text-shadow-gen/'],
  ['ChmodCalc', 'https://awictor.github.io/chmod-calc/'],
  ['Specificity', 'https://awictor.github.io/css-specificity/'],
  ['HashID', 'https://awictor.github.io/hash-id/'],
  ['Phonetic', 'https://awictor.github.io/nato-phonetic/'],
  ['PositionSize', 'https://awictor.github.io/position-size/'],
  ['RecipeScaler', 'https://awictor.github.io/recipe-scaler/'],
  ['GridGen', 'https://awictor.github.io/css-grid-gen/'],
  ['SchemaGen', 'https://awictor.github.io/json-schema-gen/'],
  ['JwtSign', 'https://awictor.github.io/jwt-sign/'],
  ['BizDays', 'https://awictor.github.io/business-days/'],
  ['BACCalc', 'https://awictor.github.io/bac-calc/'],
  ['Fixate', 'https://awictor.github.io/fixate/'],
  ['JsonToYaml', 'https://awictor.github.io/json-to-yaml/'],
  ['ColorBlind', 'https://awictor.github.io/color-blind-sim/'],
  ['MarkupMargin', 'https://awictor.github.io/markup-margin/'],
  ['Bitwise', 'https://awictor.github.io/bitwise-calc/'],
  ['IbanCheck', 'https://awictor.github.io/iban-validator/'],
  ['Uuid7', 'https://awictor.github.io/uuid7/'],
  ['Redact', 'https://awictor.github.io/redact/'],
  ['BsaCalc', 'https://awictor.github.io/bsa-calc/'],
  ['CronNext', 'https://awictor.github.io/cron-next/'],
  ['MetaTags', 'https://awictor.github.io/meta-tags/'],
  ['ClipPath', 'https://awictor.github.io/clip-path-gen/'],
  ['TimeZone', 'https://awictor.github.io/tz-convert/'],
  ['Barcode', 'https://awictor.github.io/barcode128/'],
  ['PregnancyDue', 'https://awictor.github.io/pregnancy-due/'],
  ['WordWrap', 'https://awictor.github.io/word-wrap/'],
  ['AuthHeader', 'https://awictor.github.io/auth-header/'],
  ['ColorMix', 'https://awictor.github.io/color-mix/'],
  ['ApyApr', 'https://awictor.github.io/apy-apr/'],
  ['Template', 'https://awictor.github.io/template-fill/'],
  ['JsonPath', 'https://awictor.github.io/json-path/'],
  ['UnitPrice', 'https://awictor.github.io/unit-price/'],
  ['HexDump', 'https://awictor.github.io/hex-dump/'],
  ['NanoId', 'https://awictor.github.io/nano-id/'],
  ['BloodPressure', 'https://awictor.github.io/blood-pressure/'],
  ['VatCalc', 'https://awictor.github.io/vat-calc/'],
  ['Keyframes', 'https://awictor.github.io/css-keyframes/'],
  ['Entropy', 'https://awictor.github.io/entropy-calc/'],
  ['SetOps', 'https://awictor.github.io/set-ops/'],
  ['Sparkline', 'https://awictor.github.io/sparkline/'],
  ['Columns', 'https://awictor.github.io/text-columns/'],
  ['RacePredict', 'https://awictor.github.io/race-predict/'],
  ['BudgetSplit', 'https://awictor.github.io/budget-split/'],
  ['ColorName', 'https://awictor.github.io/color-name/'],
  ['FancyText', 'https://awictor.github.io/fancy-text/'],
  ['HttpStatus', 'https://awictor.github.io/http-status/'],
  ['FuelCost', 'https://awictor.github.io/fuel-cost/'],
  ['CardCheck', 'https://awictor.github.io/card-check/'],
  ['ResistorCalc', 'https://awictor.github.io/resistor-calc/'],
  ['Neumorph', 'https://awictor.github.io/neumorphism/'],
  ['SemVer', 'https://awictor.github.io/semver-tool/'],
  ['DiceOdds', 'https://awictor.github.io/dice-odds/'],
  ['VO2Max', 'https://awictor.github.io/vo2max/'],
  ['CAGR', 'https://awictor.github.io/cagr-calc/'],
  ['UAParse', 'https://awictor.github.io/ua-parse/'],
  ['Glass', 'https://awictor.github.io/glassmorphism/'],
  ['Typography', 'https://awictor.github.io/smart-quotes/'],
  ['SecHeaders', 'https://awictor.github.io/sec-headers/'],
  ['OhmsLaw', 'https://awictor.github.io/ohms-law/'],
  ['MimeType', 'https://awictor.github.io/mime-type/'],
  ['AvgCost', 'https://awictor.github.io/avg-cost/'],
  ['Blob', 'https://awictor.github.io/blob-gen/'],
  ['Ovulation', 'https://awictor.github.io/ovulation/'],
  ['FastRead', 'https://awictor.github.io/fast-read/'],
  ['CurlToFetch', 'https://awictor.github.io/curl-to-fetch/'],
  ['CookConvert', 'https://awictor.github.io/cook-convert/'],
  ['SecretID', 'https://awictor.github.io/secret-id/'],
  ['NPV', 'https://awictor.github.io/npv-calc/'],
  ['Syllables', 'https://awictor.github.io/syllables/'],
  ['Spinner', 'https://awictor.github.io/spinner/'],
  ['FeelsLike', 'https://awictor.github.io/feels-like/'],
  ['DataURI', 'https://awictor.github.io/data-uri/'],
  ['SplitUp', 'https://awictor.github.io/split-up/'],
  ['JsonToGo', 'https://awictor.github.io/json-to-go/'],
  ['PPICalc', 'https://awictor.github.io/ppi-calc/'],
  ['Pluralize', 'https://awictor.github.io/pluralize/'],
  ['UuidInspect', 'https://awictor.github.io/uuid-inspect/'],
  ['WeightGoal', 'https://awictor.github.io/weight-goal/'],
  ['SIPrefix', 'https://awictor.github.io/si-prefix/'],
  ['StringEscape', 'https://awictor.github.io/string-escape/'],
  ['Scrollbar', 'https://awictor.github.io/scrollbar/'],
  ['RoasCalc', 'https://awictor.github.io/roas-calc/'],
  ['LinkExtract', 'https://awictor.github.io/link-extract/'],
  ['IPv6', 'https://awictor.github.io/ipv6-tool/'],
  ['AngleConvert', 'https://awictor.github.io/angle-convert/'],
  ['HtmlToMd', 'https://awictor.github.io/html-to-md/'],
  ['Karvonen', 'https://awictor.github.io/karvonen/'],
  ['TextGradient', 'https://awictor.github.io/text-gradient/'],
  ['DownloadTime', 'https://awictor.github.io/download-time/'],
  ['JSONLines', 'https://awictor.github.io/jsonl/'],
  ['Triangle', 'https://awictor.github.io/css-triangle/'],
  ['Overtime', 'https://awictor.github.io/overtime-pay/'],
  ['Deburr', 'https://awictor.github.io/deburr/'],
  ['MacAddress', 'https://awictor.github.io/mac-address/'],
  ['ChangeMaker', 'https://awictor.github.io/change-maker/'],
  ['CacheControl', 'https://awictor.github.io/cache-control/'],
  ['Numeronym', 'https://awictor.github.io/numeronym/'],
  ['Glucose', 'https://awictor.github.io/glucose-convert/'],
  ['Zodiac', 'https://awictor.github.io/zodiac/'],
  ['CronDescribe', 'https://awictor.github.io/cron-describe/'],
  ['ConicPie', 'https://awictor.github.io/conic-pie/'],
  ['StackDiscount', 'https://awictor.github.io/stack-discount/'],
  ['Beaufort', 'https://awictor.github.io/beaufort/'],
  ['Semver', 'https://awictor.github.io/semver/'],
  ['Haiku', 'https://awictor.github.io/haiku/'],
  ['HeatIndex', 'https://awictor.github.io/heat-index/'],
  ['FireCalc', 'https://awictor.github.io/fire-calc/'],
  ['GoldenRatio', 'https://awictor.github.io/golden-ratio/'],
  ['CvssCalc', 'https://awictor.github.io/cvss-calc/'],
  ['TireSize', 'https://awictor.github.io/tire-size/'],
  ['IEEE754', 'https://awictor.github.io/ieee754/'],
  ['PassiveVoice', 'https://awictor.github.io/passive-voice/'],
  ['DtiCalc', 'https://awictor.github.io/dti-calc/'],
  ['eGFR', 'https://awictor.github.io/egfr/'],
  ['JsonPointer', 'https://awictor.github.io/json-pointer/'],
  ['GlobToRegex', 'https://awictor.github.io/glob-to-regex/'],
  ['PlanetAge', 'https://awictor.github.io/planet-age/'],
  ['BaselineGrid', 'https://awictor.github.io/baseline-grid/'],
  ['WeaselWords', 'https://awictor.github.io/weasel-words/'],
  ['PackYears', 'https://awictor.github.io/pack-years/'],
  ['Vigenere', 'https://awictor.github.io/vigenere/'],
  ['CreditUtilization', 'https://awictor.github.io/credit-utilization/'],
  ['UmaskCalc', 'https://awictor.github.io/umask-calc/'],
  ['MoonPhase', 'https://awictor.github.io/moon-phase/'],
  ['Oklch', 'https://awictor.github.io/oklch/'],
  ['AnionGap', 'https://awictor.github.io/anion-gap/'],
  ['PigLatin', 'https://awictor.github.io/pig-latin/'],
  ['Backoff', 'https://awictor.github.io/backoff/'],
  ['BpmDelay', 'https://awictor.github.io/bpm-delay/'],
  ['RailFence', 'https://awictor.github.io/rail-fence/'],
  ['RuleOf72', 'https://awictor.github.io/rule-of-72/'],
  ['SnowflakeId', 'https://awictor.github.io/snowflake-id/'],
  ['HexAlpha', 'https://awictor.github.io/hex-alpha/'],
  ['QTc', 'https://awictor.github.io/qtc/'],
  ['Leetspeak', 'https://awictor.github.io/leetspeak/'],
  ['PetAge', 'https://awictor.github.io/pet-age/'],
  ['Base85', 'https://awictor.github.io/base85/'],
  ['LetterSpacing', 'https://awictor.github.io/letter-spacing/'],
  ['Annuity', 'https://awictor.github.io/annuity/'],
  ['Soundex', 'https://awictor.github.io/soundex/'],
  ['BirthdayParadox', 'https://awictor.github.io/birthday-paradox/'],
  ['ColorTemp', 'https://awictor.github.io/color-temp/'],
  ['TwosComplement', 'https://awictor.github.io/twos-complement/'],
  ['CockcroftGault', 'https://awictor.github.io/cockcroft-gault/'],
  ['Anagram', 'https://awictor.github.io/anagram/'],
  ['IsoWeek', 'https://awictor.github.io/iso-week/'],
  ['XorCipher', 'https://awictor.github.io/xor-cipher/'],
  ['CostPerUse', 'https://awictor.github.io/cost-per-use/'],
  ['CorrectedCalcium', 'https://awictor.github.io/corrected-calcium/'],
  ['Braille', 'https://awictor.github.io/braille/'],
  ['CookieParser', 'https://awictor.github.io/cookie-parser/'],
  ['CssPattern', 'https://awictor.github.io/css-pattern/'],
  ['OvenTemp', 'https://awictor.github.io/oven-temp/'],
  ['Bogo', 'https://awictor.github.io/bogo/'],
  ['MaintenanceFluids', 'https://awictor.github.io/maintenance-fluids/'],
  ['Acronym', 'https://awictor.github.io/acronym/'],
  ['AsciiTable', 'https://awictor.github.io/ascii-table/'],
  ['PasswordPolicy', 'https://awictor.github.io/password-policy/'],
  ['SpacingScale', 'https://awictor.github.io/spacing-scale/'],
  ['NoteFrequency', 'https://awictor.github.io/note-frequency/'],
  ['QuotedPrintable', 'https://awictor.github.io/quoted-printable/'],
  ['RaiseCalc', 'https://awictor.github.io/raise-calc/'],
  ['Osmolality', 'https://awictor.github.io/osmolality/'],
  ['APCA Contrast', 'https://awictor.github.io/apca-contrast/'],
  ['Playfair', 'https://awictor.github.io/playfair/'],
  ['Invisible Characters', 'https://awictor.github.io/invisible-chars/'],
  ['Bond Calculator', 'https://awictor.github.io/bond-calc/'],
  ['Punycode / IDN', 'https://awictor.github.io/punycode/'],
  ['Dew Point', 'https://awictor.github.io/dew-point/'],
  ['CHA₂DS₂-VASc', 'https://awictor.github.io/chads-vasc/'],
  ['CMYK Converter', 'https://awictor.github.io/cmyk/'],
  ['Affine Cipher', 'https://awictor.github.io/affine-cipher/'],
  ['Keyword Density', 'https://awictor.github.io/keyword-density/'],
  ['Refinance Calculator', 'https://awictor.github.io/refinance-calc/'],
  ['HTML to JSX', 'https://awictor.github.io/html-to-jsx/'],
  ['Pizza Dough', 'https://awictor.github.io/pizza-dough/'],
  ['Parkland Formula', 'https://awictor.github.io/parkland/'],
  ['HSV / HSB Converter', 'https://awictor.github.io/hsv-convert/'],
  ['Bacon Cipher', 'https://awictor.github.io/bacon-cipher/'],
  ['Letter Frequency', 'https://awictor.github.io/letter-frequency/'],
  ['401(k) Match', 'https://awictor.github.io/401k-match/'],
  ['JSON Diff', 'https://awictor.github.io/json-diff/'],
  ['Coffee Ratio', 'https://awictor.github.io/coffee-ratio/'],
  ['Cycling Power Zones', 'https://awictor.github.io/power-zones/'],
  ['HWB Converter', 'https://awictor.github.io/hwb-color/'],
  ['Polybius Square', 'https://awictor.github.io/polybius/'],
  ['Wordiness Reducer', 'https://awictor.github.io/wordiness/'],
  ['Dividend Calculator', 'https://awictor.github.io/dividend-calc/'],
  ['Checksum', 'https://awictor.github.io/checksum/'],
  ['Paint Calculator', 'https://awictor.github.io/paint-calc/'],
  ['Corrected Sodium', 'https://awictor.github.io/corrected-sodium/'],
  ['CIELAB + ΔE', 'https://awictor.github.io/cielab/'],
  ['Columnar Transposition', 'https://awictor.github.io/columnar/'],
  ['Adverb Finder', 'https://awictor.github.io/adverb-finder/'],
  ['Capital Gains', 'https://awictor.github.io/capital-gains/'],
  ['JSON to XML', 'https://awictor.github.io/json-to-xml/'],
  ['Tile Calculator', 'https://awictor.github.io/tile-calc/'],
  ['Wilks Calculator', 'https://awictor.github.io/wilks/'],
  ['Viewport Units', 'https://awictor.github.io/viewport-units/'],
  ['HOTP Generator', 'https://awictor.github.io/hotp/'],
  ['Cliché Finder', 'https://awictor.github.io/cliche-finder/'],
  ['Payback Period', 'https://awictor.github.io/payback-period/'],
  ['JSON to Rust', 'https://awictor.github.io/json-to-rust/'],
  ['Concrete Calculator', 'https://awictor.github.io/concrete-calc/'],
  ["Winters' Formula", 'https://awictor.github.io/winters-formula/'],
  ['Color Steps', 'https://awictor.github.io/color-steps/'],
  ['CSS Units Converter', 'https://awictor.github.io/css-units/'],
  ['Gronsfeld Cipher', 'https://awictor.github.io/gronsfeld/'],
  ['Lexical Diversity', 'https://awictor.github.io/lexical-diversity/'],
  ['Commission Calculator', 'https://awictor.github.io/commission-calc/'],
  ['String Hash', 'https://awictor.github.io/string-hash/'],
  ['Mulch &amp; Soil', 'https://awictor.github.io/mulch-calc/'],
  ['Free Water Deficit', 'https://awictor.github.io/free-water-deficit/'],
  ['Palette from Image', 'https://awictor.github.io/image-palette/'],
  ['Nihilist Cipher', 'https://awictor.github.io/nihilist/'],
  ['Gematria Calculator', 'https://awictor.github.io/gematria/'],
  ['Home Affordability', 'https://awictor.github.io/home-affordability/'],
  ['JSON to Python', 'https://awictor.github.io/json-to-python/'],
  ['Lightning Distance', 'https://awictor.github.io/lightning-distance/'],
  ['FENa Calculator', 'https://awictor.github.io/fena/'],
  ['SVG Wave', 'https://awictor.github.io/svg-wave/'],
  ['Passphrase', 'https://awictor.github.io/passphrase/'],
  ['Sentence Rhythm', 'https://awictor.github.io/sentence-rhythm/'],
  ['Card Payoff', 'https://awictor.github.io/card-payoff/'],
  ['JsonToSql', 'https://awictor.github.io/json-to-sql/'],
  ['Wallpaper Calculator', 'https://awictor.github.io/wallpaper-calc/'],
  ['IV Drip Rate', 'https://awictor.github.io/drip-rate/'],
  ['Bcrypt Inspector', 'https://awictor.github.io/bcrypt-inspector/'],
  ['Inclusive Language', 'https://awictor.github.io/inclusive-language/'],
  ['Emergency Fund', 'https://awictor.github.io/emergency-fund/'],
  ['CRC Calculator', 'https://awictor.github.io/crc-calc/'],
  ['Aquarium Volume', 'https://awictor.github.io/aquarium-volume/'],
  ['Opioid MME', 'https://awictor.github.io/opioid-mme/'],
];

let n = 0; const check = (name, fn) => { fn(); n++; console.log('  ok -', name); };

for (const [name, url] of tools) {
  check(`links ${name}`, () => {
    assert.ok(html.includes(url), `missing URL ${url}`);
    assert.ok(html.includes('>' + name + '<'), `missing name ${name}`);
  });
}
check('exactly 343 tool cards', () => {
  assert.equal((html.match(/class="card"/g) || []).length, 343);
});
check('tools grouped into category sections', () => {
  assert.equal((html.match(/class="cat"/g) || []).length, 7);
  for (const c of ['Finance', 'Developer', 'Design', 'Security', 'Writing', 'Health', 'Everyday'])
    assert.ok(html.includes('<h3>' + c) || html.includes(c + '</h3>') || new RegExp('<h3>'+c).test(html), 'missing category ' + c);
});
check('valid JSON-LD ItemList with 343 items', () => {
  const m = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
  assert.ok(m, 'no JSON-LD block');
  const data = JSON.parse(m[1]);
  assert.equal(data['@type'], 'ItemList');
  assert.equal(data.itemListElement.length, 343);
  assert.equal(data.itemListElement[0].item.url, tools[0][1]);
});

check('sitemap.xml lists all 343 pages', () => {
  const sm = readFileSync(join(__dirname, '..', 'sitemap.xml'), 'utf8');
  const urls = ['toolkit', ...tools.map(t => t[1])];
  assert.equal((sm.match(/<loc>/g) || []).length, 344);
  assert.ok(sm.includes('https://awictor.github.io/toolkit/'));
  for (const [, url] of tools) assert.ok(sm.includes(url), 'sitemap missing ' + url);
});

// Evaluate the hub script in a minimal DOM stub to exercise the pure filter.
function el(){ return {value:'',textContent:'',style:{},className:'',getAttribute(){return null;},setAttribute(){},addEventListener(){},querySelectorAll(){return[];},onclick:null}; }
globalThis.document={getElementById:()=>el(),querySelectorAll:()=>[],documentElement:el()};
globalThis.localStorage={getItem:()=>null,setItem(){},removeItem(){}};
globalThis.window={matchMedia:()=>({matches:false})};
globalThis.matchMedia=globalThis.window.matchMedia;
const js=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).sort((a,b)=>b.length-a.length)[0];
eval(js+`\n;globalThis.__t={filterTools};`);
const filterTools=globalThis.__t.filterTools;

check('filterTools: matches name or description, case-insensitive', () => {
  const items=[{name:'MarginMaster',desc:'Amazon FBA true-profit'},{name:'Payoff',desc:'debt snowball'},{name:'NestEgg',desc:'compound interest'}];
  assert.equal(filterTools(items,'').length, 3);
  assert.deepEqual(filterTools(items,'debt').map(i=>i.name), ['Payoff']);
  assert.deepEqual(filterTools(items,'AMAZON').map(i=>i.name), ['MarginMaster']);
  assert.deepEqual(filterTools(items,'interest').map(i=>i.name), ['NestEgg']);
  assert.equal(filterTools(items,'zzz').length, 0);
  assert.equal(filterTools(items,'   ').length, 3); // whitespace-only = no filter
});
check('filterTools: supports a combined text field', () => {
  const items=[{text:'Runway SaaS metrics'},{text:'RateRight freelance'}];
  assert.deepEqual(filterTools(items,'saas'), [items[0]]);
});

console.log(`\n${n} checks passed.`);
