// Link-integrity test for the Toolkit hub: every tool must be present and linked.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, '..', 'index.html'), 'utf8');

const tools = [
  ['MarginMaster', 'https://awictor.github.io/margin-master/'],
  ['Runway', 'https://awictor.github.io/runway-calc/'],
  ['RateRight', 'https://awictor.github.io/rate-right/'],
  ['Payoff', 'https://awictor.github.io/payoff/'],
  ['BreakEven', 'https://awictor.github.io/breakeven/'],
  ['TipSplit', 'https://awictor.github.io/tip-split/'],
  ['LoanCalc', 'https://awictor.github.io/loan-calc/'],
  ['NestEgg', 'https://awictor.github.io/nest-egg/'],
  ['PassForge', 'https://awictor.github.io/pass-forge/'],
  ['Contrast', 'https://awictor.github.io/contrast/'],
  ['CronPal', 'https://awictor.github.io/cron-pal/'],
  ['JWTPeek', 'https://awictor.github.io/jwt-peek/'],
  ['WordCount', 'https://awictor.github.io/word-count/'],
  ['EpochConvert', 'https://awictor.github.io/epoch-convert/'],
  ['ColorConvert', 'https://awictor.github.io/color-convert/'],
  ['CaseKit', 'https://awictor.github.io/case-kit/'],
  ['EncodeKit', 'https://awictor.github.io/encode-kit/'],
  ['UUIDGen', 'https://awictor.github.io/uuid-gen/'],
  ['JSONFormat', 'https://awictor.github.io/json-format/'],
  ['DiffCheck', 'https://awictor.github.io/diff-check/'],
  ['LoremGen', 'https://awictor.github.io/lorem-gen/'],
  ['HashGen', 'https://awictor.github.io/hash-gen/'],
  ['BaseConvert', 'https://awictor.github.io/base-convert/'],
  ['AspectRatio', 'https://awictor.github.io/aspect-ratio/'],
  ['PercentCalc', 'https://awictor.github.io/percent-calc/'],
  ['CSVJSON', 'https://awictor.github.io/csv-json/'],
  ['BMICalc', 'https://awictor.github.io/bmi-calc/'],
  ['TDEECalc', 'https://awictor.github.io/tdee-calc/'],
  ['DateDiff', 'https://awictor.github.io/date-diff/'],
  ['TaxCalc', 'https://awictor.github.io/tax-calc/'],
  ['RomanNumeral', 'https://awictor.github.io/roman-numeral/'],
  ['UnitConvert', 'https://awictor.github.io/unit-convert/'],
  ['DiscountCalc', 'https://awictor.github.io/discount-calc/'],
  ['GradeCalc', 'https://awictor.github.io/grade-calc/'],
  ['PaceCalc', 'https://awictor.github.io/pace-calc/'],
  ['PxRem', 'https://awictor.github.io/px-rem/'],
  ['LineTools', 'https://awictor.github.io/line-tools/'],
  ['RandomPick', 'https://awictor.github.io/random-pick/'],
  ['RegexTest', 'https://awictor.github.io/regex-test/'],
  ['MorseCode', 'https://awictor.github.io/morse-code/'],
  ['WageCalc', 'https://awictor.github.io/wage-calc/'],
  ['URLParse', 'https://awictor.github.io/url-parse/'],
  ['TypeScale', 'https://awictor.github.io/type-scale/'],
  ['OneRepMax', 'https://awictor.github.io/one-rep-max/'],
  ['HTMLEntities', 'https://awictor.github.io/html-entities/'],
  ['StrengthCheck', 'https://awictor.github.io/strength-check/'],
  ['SaveGoal', 'https://awictor.github.io/save-goal/'],
  ['TitleCase', 'https://awictor.github.io/title-case/'],
  ['AgeCalc', 'https://awictor.github.io/age-calc/'],
  ['InflationCalc', 'https://awictor.github.io/inflation-calc/'],
  ['WaterIntake', 'https://awictor.github.io/water-intake/'],
  ['FractionConvert', 'https://awictor.github.io/fraction-convert/'],
  ['ClampGen', 'https://awictor.github.io/clamp-gen/'],
  ['Slugify', 'https://awictor.github.io/slugify/'],
  ['MacroCalc', 'https://awictor.github.io/macro-calc/'],
  ['ROICalc', 'https://awictor.github.io/roi-calc/'],
  ['SubnetCalc', 'https://awictor.github.io/subnet-calc/'],
  ['NumWords', 'https://awictor.github.io/num-words/'],
  ['HoursCalc', 'https://awictor.github.io/hours-calc/'],
  ['ShadeGen', 'https://awictor.github.io/shade-gen/'],
  ['AuthCode', 'https://awictor.github.io/auth-code/'],
  ['MdTable', 'https://awictor.github.io/md-table/'],
  ['HeartZones', 'https://awictor.github.io/heart-zones/'],
  ['CSPKit', 'https://awictor.github.io/csp-kit/'],
  ['GradientGen', 'https://awictor.github.io/gradient-gen/'],
  ['MdPreview', 'https://awictor.github.io/md-preview/'],
  ['ByteSize', 'https://awictor.github.io/byte-size/'],
  ['FindReplace', 'https://awictor.github.io/find-replace/'],
  ['HmacGen', 'https://awictor.github.io/hmac-gen/'],
  ['JsonToTs', 'https://awictor.github.io/json-to-ts/'],
  ['BodyFat', 'https://awictor.github.io/body-fat/'],
  ['MathKit', 'https://awictor.github.io/math-kit/'],
  ['ShadowGen', 'https://awictor.github.io/shadow-gen/'],
  ['TokenGen', 'https://awictor.github.io/token-gen/'],
  ['Amortize', 'https://awictor.github.io/amortize/'],
  ['Similarity', 'https://awictor.github.io/similarity/'],
  ['CheckDigit', 'https://awictor.github.io/check-digit/'],
  ['Easing', 'https://awictor.github.io/easing/'],
  ['CipherNote', 'https://awictor.github.io/cipher-note/'],
  ['Duration', 'https://awictor.github.io/duration/'],
  ['Harmony', 'https://awictor.github.io/color-harmony/'],
  ['DotEnv', 'https://awictor.github.io/dotenv/'],
  ['TextClean', 'https://awictor.github.io/text-clean/'],
  ['IdealWeight', 'https://awictor.github.io/ideal-weight/'],
  ['SriGen', 'https://awictor.github.io/sri-gen/'],
  ['RotCipher', 'https://awictor.github.io/rot-cipher/'],
  ['A1C', 'https://awictor.github.io/a1c/'],
  ['GPACalc', 'https://awictor.github.io/gpa-calc/'],
  ['FilterGen', 'https://awictor.github.io/filter-gen/'],
  ['UlidGen', 'https://awictor.github.io/ulid-gen/'],
  ['SciNotation', 'https://awictor.github.io/sci-notation/'],
  ['DueDate', 'https://awictor.github.io/due-date/'],
  ['Base32', 'https://awictor.github.io/base32/'],
  ['WordFreq', 'https://awictor.github.io/word-freq/'],
  ['Uuid5', 'https://awictor.github.io/uuid5/'],
  ['CalBurn', 'https://awictor.github.io/cal-burn/'],
  ['TextReverse', 'https://awictor.github.io/text-reverse/'],
  ['RadiusGen', 'https://awictor.github.io/radius-gen/'],
  ['JsonToCsv', 'https://awictor.github.io/json-to-csv/'],
  ['SleepCalc', 'https://awictor.github.io/sleep-calc/'],
  ['QueryString', 'https://awictor.github.io/query-string/'],
  ['Readability', 'https://awictor.github.io/readability/'],
  ['Base58', 'https://awictor.github.io/base58/'],
  ['TransformGen', 'https://awictor.github.io/transform-gen/'],
  ['WaistHeight', 'https://awictor.github.io/waist-height/'],
  ['Unicode', 'https://awictor.github.io/unicode/'],
  ['MdToc', 'https://awictor.github.io/md-toc/'],
  ['Crc32', 'https://awictor.github.io/crc32/'],
  ['TextShadowGen', 'https://awictor.github.io/text-shadow-gen/'],
  ['ChmodCalc', 'https://awictor.github.io/chmod-calc/'],
  ['Specificity', 'https://awictor.github.io/css-specificity/'],
  ['HashID', 'https://awictor.github.io/hash-id/'],
  ['Phonetic', 'https://awictor.github.io/nato-phonetic/'],
  ['PositionSize', 'https://awictor.github.io/position-size/'],
  ['RecipeScaler', 'https://awictor.github.io/recipe-scaler/'],
  ['GridGen', 'https://awictor.github.io/css-grid-gen/'],
  ['SchemaGen', 'https://awictor.github.io/json-schema-gen/'],
  ['JwtSign', 'https://awictor.github.io/jwt-sign/'],
  ['BizDays', 'https://awictor.github.io/business-days/'],
  ['BACCalc', 'https://awictor.github.io/bac-calc/'],
  ['Fixate', 'https://awictor.github.io/fixate/'],
  ['JsonToYaml', 'https://awictor.github.io/json-to-yaml/'],
  ['ColorBlind', 'https://awictor.github.io/color-blind-sim/'],
  ['MarkupMargin', 'https://awictor.github.io/markup-margin/'],
  ['Bitwise', 'https://awictor.github.io/bitwise-calc/'],
  ['IbanCheck', 'https://awictor.github.io/iban-validator/'],
  ['Uuid7', 'https://awictor.github.io/uuid7/'],
  ['Redact', 'https://awictor.github.io/redact/'],
  ['BsaCalc', 'https://awictor.github.io/bsa-calc/'],
  ['CronNext', 'https://awictor.github.io/cron-next/'],
  ['MetaTags', 'https://awictor.github.io/meta-tags/'],
  ['ClipPath', 'https://awictor.github.io/clip-path-gen/'],
  ['TimeZone', 'https://awictor.github.io/tz-convert/'],
  ['Barcode', 'https://awictor.github.io/barcode128/'],
  ['PregnancyDue', 'https://awictor.github.io/pregnancy-due/'],
  ['WordWrap', 'https://awictor.github.io/word-wrap/'],
  ['AuthHeader', 'https://awictor.github.io/auth-header/'],
  ['ColorMix', 'https://awictor.github.io/color-mix/'],
  ['ApyApr', 'https://awictor.github.io/apy-apr/'],
  ['Template', 'https://awictor.github.io/template-fill/'],
  ['JsonPath', 'https://awictor.github.io/json-path/'],
  ['UnitPrice', 'https://awictor.github.io/unit-price/'],
  ['HexDump', 'https://awictor.github.io/hex-dump/'],
  ['NanoId', 'https://awictor.github.io/nano-id/'],
  ['BloodPressure', 'https://awictor.github.io/blood-pressure/'],
  ['VatCalc', 'https://awictor.github.io/vat-calc/'],
  ['Keyframes', 'https://awictor.github.io/css-keyframes/'],
  ['Entropy', 'https://awictor.github.io/entropy-calc/'],
  ['SetOps', 'https://awictor.github.io/set-ops/'],
  ['Sparkline', 'https://awictor.github.io/sparkline/'],
  ['Columns', 'https://awictor.github.io/text-columns/'],
  ['RacePredict', 'https://awictor.github.io/race-predict/'],
  ['BudgetSplit', 'https://awictor.github.io/budget-split/'],
  ['ColorName', 'https://awictor.github.io/color-name/'],
  ['FancyText', 'https://awictor.github.io/fancy-text/'],
  ['HttpStatus', 'https://awictor.github.io/http-status/'],
  ['FuelCost', 'https://awictor.github.io/fuel-cost/'],
  ['CardCheck', 'https://awictor.github.io/card-check/'],
  ['ResistorCalc', 'https://awictor.github.io/resistor-calc/'],
  ['Neumorph', 'https://awictor.github.io/neumorphism/'],
  ['SemVer', 'https://awictor.github.io/semver-tool/'],
  ['DiceOdds', 'https://awictor.github.io/dice-odds/'],
  ['VO2Max', 'https://awictor.github.io/vo2max/'],
  ['CAGR', 'https://awictor.github.io/cagr-calc/'],
  ['UAParse', 'https://awictor.github.io/ua-parse/'],
  ['Glass', 'https://awictor.github.io/glassmorphism/'],
  ['Typography', 'https://awictor.github.io/smart-quotes/'],
  ['SecHeaders', 'https://awictor.github.io/sec-headers/'],
  ['OhmsLaw', 'https://awictor.github.io/ohms-law/'],
  ['MimeType', 'https://awictor.github.io/mime-type/'],
  ['AvgCost', 'https://awictor.github.io/avg-cost/'],
  ['Blob', 'https://awictor.github.io/blob-gen/'],
  ['Ovulation', 'https://awictor.github.io/ovulation/'],
  ['FastRead', 'https://awictor.github.io/fast-read/'],
  ['CurlToFetch', 'https://awictor.github.io/curl-to-fetch/'],
  ['CookConvert', 'https://awictor.github.io/cook-convert/'],
  ['SecretID', 'https://awictor.github.io/secret-id/'],
  ['NPV', 'https://awictor.github.io/npv-calc/'],
  ['Syllables', 'https://awictor.github.io/syllables/'],
  ['Spinner', 'https://awictor.github.io/spinner/'],
  ['FeelsLike', 'https://awictor.github.io/feels-like/'],
  ['DataURI', 'https://awictor.github.io/data-uri/'],
  ['SplitUp', 'https://awictor.github.io/split-up/'],
  ['JsonToGo', 'https://awictor.github.io/json-to-go/'],
  ['PPICalc', 'https://awictor.github.io/ppi-calc/'],
  ['Pluralize', 'https://awictor.github.io/pluralize/'],
  ['UuidInspect', 'https://awictor.github.io/uuid-inspect/'],
  ['WeightGoal', 'https://awictor.github.io/weight-goal/'],
  ['SIPrefix', 'https://awictor.github.io/si-prefix/'],
  ['StringEscape', 'https://awictor.github.io/string-escape/'],
  ['Scrollbar', 'https://awictor.github.io/scrollbar/'],
  ['RoasCalc', 'https://awictor.github.io/roas-calc/'],
  ['LinkExtract', 'https://awictor.github.io/link-extract/'],
  ['IPv6', 'https://awictor.github.io/ipv6-tool/'],
  ['AngleConvert', 'https://awictor.github.io/angle-convert/'],
  ['HtmlToMd', 'https://awictor.github.io/html-to-md/'],
  ['Karvonen', 'https://awictor.github.io/karvonen/'],
  ['TextGradient', 'https://awictor.github.io/text-gradient/'],
  ['DownloadTime', 'https://awictor.github.io/download-time/'],
  ['JSONLines', 'https://awictor.github.io/jsonl/'],
  ['Triangle', 'https://awictor.github.io/css-triangle/'],
  ['Overtime', 'https://awictor.github.io/overtime-pay/'],
  ['Deburr', 'https://awictor.github.io/deburr/'],
  ['MacAddress', 'https://awictor.github.io/mac-address/'],
  ['ChangeMaker', 'https://awictor.github.io/change-maker/'],
  ['CacheControl', 'https://awictor.github.io/cache-control/'],
  ['Numeronym', 'https://awictor.github.io/numeronym/'],
  ['Glucose', 'https://awictor.github.io/glucose-convert/'],
  ['Zodiac', 'https://awictor.github.io/zodiac/'],
  ['CronDescribe', 'https://awictor.github.io/cron-describe/'],
  ['ConicPie', 'https://awictor.github.io/conic-pie/'],
  ['StackDiscount', 'https://awictor.github.io/stack-discount/'],
  ['Beaufort', 'https://awictor.github.io/beaufort/'],
  ['Semver', 'https://awictor.github.io/semver/'],
  ['Haiku', 'https://awictor.github.io/haiku/'],
  ['HeatIndex', 'https://awictor.github.io/heat-index/'],
  ['FireCalc', 'https://awictor.github.io/fire-calc/'],
  ['GoldenRatio', 'https://awictor.github.io/golden-ratio/'],
  ['CvssCalc', 'https://awictor.github.io/cvss-calc/'],
  ['TireSize', 'https://awictor.github.io/tire-size/'],
  ['IEEE754', 'https://awictor.github.io/ieee754/'],
  ['PassiveVoice', 'https://awictor.github.io/passive-voice/'],
  ['DtiCalc', 'https://awictor.github.io/dti-calc/'],
  ['eGFR', 'https://awictor.github.io/egfr/'],
  ['JsonPointer', 'https://awictor.github.io/json-pointer/'],
  ['GlobToRegex', 'https://awictor.github.io/glob-to-regex/'],
  ['PlanetAge', 'https://awictor.github.io/planet-age/'],
  ['BaselineGrid', 'https://awictor.github.io/baseline-grid/'],
  ['WeaselWords', 'https://awictor.github.io/weasel-words/'],
  ['PackYears', 'https://awictor.github.io/pack-years/'],
  ['Vigenere', 'https://awictor.github.io/vigenere/'],
  ['CreditUtilization', 'https://awictor.github.io/credit-utilization/'],
  ['UmaskCalc', 'https://awictor.github.io/umask-calc/'],
  ['MoonPhase', 'https://awictor.github.io/moon-phase/'],
  ['Oklch', 'https://awictor.github.io/oklch/'],
  ['AnionGap', 'https://awictor.github.io/anion-gap/'],
  ['PigLatin', 'https://awictor.github.io/pig-latin/'],
  ['Backoff', 'https://awictor.github.io/backoff/'],
  ['BpmDelay', 'https://awictor.github.io/bpm-delay/'],
  ['RailFence', 'https://awictor.github.io/rail-fence/'],
  ['RuleOf72', 'https://awictor.github.io/rule-of-72/'],
  ['SnowflakeId', 'https://awictor.github.io/snowflake-id/'],
  ['HexAlpha', 'https://awictor.github.io/hex-alpha/'],
  ['QTc', 'https://awictor.github.io/qtc/'],
  ['Leetspeak', 'https://awictor.github.io/leetspeak/'],
  ['PetAge', 'https://awictor.github.io/pet-age/'],
  ['Base85', 'https://awictor.github.io/base85/'],
  ['LetterSpacing', 'https://awictor.github.io/letter-spacing/'],
  ['Annuity', 'https://awictor.github.io/annuity/'],
  ['Soundex', 'https://awictor.github.io/soundex/'],
  ['BirthdayParadox', 'https://awictor.github.io/birthday-paradox/'],
  ['ColorTemp', 'https://awictor.github.io/color-temp/'],
  ['TwosComplement', 'https://awictor.github.io/twos-complement/'],
  ['CockcroftGault', 'https://awictor.github.io/cockcroft-gault/'],
  ['Anagram', 'https://awictor.github.io/anagram/'],
  ['IsoWeek', 'https://awictor.github.io/iso-week/'],
  ['XorCipher', 'https://awictor.github.io/xor-cipher/'],
  ['CostPerUse', 'https://awictor.github.io/cost-per-use/'],
  ['CorrectedCalcium', 'https://awictor.github.io/corrected-calcium/'],
  ['Braille', 'https://awictor.github.io/braille/'],
  ['CookieParser', 'https://awictor.github.io/cookie-parser/'],
  ['CssPattern', 'https://awictor.github.io/css-pattern/'],
  ['OvenTemp', 'https://awictor.github.io/oven-temp/'],
  ['Bogo', 'https://awictor.github.io/bogo/'],
  ['MaintenanceFluids', 'https://awictor.github.io/maintenance-fluids/'],
  ['Acronym', 'https://awictor.github.io/acronym/'],
  ['AsciiTable', 'https://awictor.github.io/ascii-table/'],
  ['PasswordPolicy', 'https://awictor.github.io/password-policy/'],
  ['SpacingScale', 'https://awictor.github.io/spacing-scale/'],
  ['NoteFrequency', 'https://awictor.github.io/note-frequency/'],
  ['QuotedPrintable', 'https://awictor.github.io/quoted-printable/'],
  ['RaiseCalc', 'https://awictor.github.io/raise-calc/'],
  ['Osmolality', 'https://awictor.github.io/osmolality/'],
  ['APCA Contrast', 'https://awictor.github.io/apca-contrast/'],
  ['Playfair', 'https://awictor.github.io/playfair/'],
  ['Invisible Characters', 'https://awictor.github.io/invisible-chars/'],
  ['Bond Calculator', 'https://awictor.github.io/bond-calc/'],
  ['Punycode / IDN', 'https://awictor.github.io/punycode/'],
  ['Dew Point', 'https://awictor.github.io/dew-point/'],
  ['CHA₂DS₂-VASc', 'https://awictor.github.io/chads-vasc/'],
  ['CMYK Converter', 'https://awictor.github.io/cmyk/'],
  ['Affine Cipher', 'https://awictor.github.io/affine-cipher/'],
  ['Keyword Density', 'https://awictor.github.io/keyword-density/'],
  ['Refinance Calculator', 'https://awictor.github.io/refinance-calc/'],
  ['HTML to JSX', 'https://awictor.github.io/html-to-jsx/'],
  ['Pizza Dough', 'https://awictor.github.io/pizza-dough/'],
  ['Parkland Formula', 'https://awictor.github.io/parkland/'],
  ['HSV / HSB Converter', 'https://awictor.github.io/hsv-convert/'],
  ['Bacon Cipher', 'https://awictor.github.io/bacon-cipher/'],
  ['Letter Frequency', 'https://awictor.github.io/letter-frequency/'],
  ['401(k) Match', 'https://awictor.github.io/401k-match/'],
  ['JSON Diff', 'https://awictor.github.io/json-diff/'],
  ['Coffee Ratio', 'https://awictor.github.io/coffee-ratio/'],
  ['Cycling Power Zones', 'https://awictor.github.io/power-zones/'],
  ['HWB Converter', 'https://awictor.github.io/hwb-color/'],
  ['Polybius Square', 'https://awictor.github.io/polybius/'],
  ['Wordiness Reducer', 'https://awictor.github.io/wordiness/'],
  ['Dividend Calculator', 'https://awictor.github.io/dividend-calc/'],
  ['Checksum', 'https://awictor.github.io/checksum/'],
  ['Paint Calculator', 'https://awictor.github.io/paint-calc/'],
  ['Corrected Sodium', 'https://awictor.github.io/corrected-sodium/'],
  ['CIELAB + ΔE', 'https://awictor.github.io/cielab/'],
  ['Columnar Transposition', 'https://awictor.github.io/columnar/'],
  ['Adverb Finder', 'https://awictor.github.io/adverb-finder/'],
  ['Capital Gains', 'https://awictor.github.io/capital-gains/'],
  ['JSON to XML', 'https://awictor.github.io/json-to-xml/'],
  ['Tile Calculator', 'https://awictor.github.io/tile-calc/'],
  ['Wilks Calculator', 'https://awictor.github.io/wilks/'],
  ['Viewport Units', 'https://awictor.github.io/viewport-units/'],
  ['HOTP Generator', 'https://awictor.github.io/hotp/'],
  ['Cliché Finder', 'https://awictor.github.io/cliche-finder/'],
  ['Payback Period', 'https://awictor.github.io/payback-period/'],
  ['JSON to Rust', 'https://awictor.github.io/json-to-rust/'],
  ['Concrete Calculator', 'https://awictor.github.io/concrete-calc/'],
  ["Winters' Formula", 'https://awictor.github.io/winters-formula/'],
  ['Color Steps', 'https://awictor.github.io/color-steps/'],
  ['CSS Units Converter', 'https://awictor.github.io/css-units/'],
  ['Gronsfeld Cipher', 'https://awictor.github.io/gronsfeld/'],
  ['Lexical Diversity', 'https://awictor.github.io/lexical-diversity/'],
  ['Commission Calculator', 'https://awictor.github.io/commission-calc/'],
  ['String Hash', 'https://awictor.github.io/string-hash/'],
  ['Mulch &amp; Soil', 'https://awictor.github.io/mulch-calc/'],
  ['Free Water Deficit', 'https://awictor.github.io/free-water-deficit/'],
  ['Palette from Image', 'https://awictor.github.io/image-palette/'],
  ['Nihilist Cipher', 'https://awictor.github.io/nihilist/'],
  ['Gematria Calculator', 'https://awictor.github.io/gematria/'],
  ['Home Affordability', 'https://awictor.github.io/home-affordability/'],
  ['JSON to Python', 'https://awictor.github.io/json-to-python/'],
  ['Lightning Distance', 'https://awictor.github.io/lightning-distance/'],
  ['FENa Calculator', 'https://awictor.github.io/fena/'],
  ['SVG Wave', 'https://awictor.github.io/svg-wave/'],
  ['Passphrase', 'https://awictor.github.io/passphrase/'],
  ['Sentence Rhythm', 'https://awictor.github.io/sentence-rhythm/'],
  ['Card Payoff', 'https://awictor.github.io/card-payoff/'],
  ['JsonToSql', 'https://awictor.github.io/json-to-sql/'],
  ['Wallpaper Calculator', 'https://awictor.github.io/wallpaper-calc/'],
  ['IV Drip Rate', 'https://awictor.github.io/drip-rate/'],
  ['Bifid Cipher', 'https://awictor.github.io/bifid/'],
  ['Text Summarizer', 'https://awictor.github.io/summarizer/'],
  ['Coast FIRE', 'https://awictor.github.io/coast-fire/'],
  ['JsonToZod', 'https://awictor.github.io/json-to-zod/'],
  ['Pizza Value', 'https://awictor.github.io/pizza-value/'],
  ['LDL Cholesterol', 'https://awictor.github.io/ldl-calc/'],
  ['Verhoeff Check Digit', 'https://awictor.github.io/verhoeff/'],
  ['Manuscript Stats', 'https://awictor.github.io/manuscript-stats/'],
  ['Rent vs Buy', 'https://awictor.github.io/rent-vs-buy/'],
  ['JsonFlatten', 'https://awictor.github.io/json-flatten/'],
  ['Stair Calculator', 'https://awictor.github.io/stair-calc/'],
  ['Wells Score (DVT)', 'https://awictor.github.io/wells-score/'],
  ['Autokey Cipher', 'https://awictor.github.io/autokey-cipher/'],
  ['Word Echo Finder', 'https://awictor.github.io/word-echo/'],
  ['Biweekly Mortgage', 'https://awictor.github.io/biweekly-mortgage/'],
  ['JsonToKotlin', 'https://awictor.github.io/json-to-kotlin/'],
  ['Roof Pitch', 'https://awictor.github.io/roof-pitch/'],
  ['CURB-65', 'https://awictor.github.io/curb-65/'],
  ['Beaufort Cipher', 'https://awictor.github.io/beaufort-cipher/'],
  ['Alliteration Finder', 'https://awictor.github.io/alliteration/'],
  ['Mortgage Points', 'https://awictor.github.io/mortgage-points/'],
  ['CsvToSql', 'https://awictor.github.io/csv-to-sql/'],
  ['Firewood Calculator', 'https://awictor.github.io/firewood-calc/'],
  ['Centor / McIsaac', 'https://awictor.github.io/centor-score/'],
  ['Trifid Cipher', 'https://awictor.github.io/trifid/'],
  ['Pangram Checker', 'https://awictor.github.io/pangram/'],
  ['Extra Payment', 'https://awictor.github.io/extra-payment/'],
  ['IniJson', 'https://awictor.github.io/ini-json/'],
  ['Meat Temperature Guide', 'https://awictor.github.io/meat-temp/'],
  ['MELD-Na', 'https://awictor.github.io/meld-na/'],
  ['Four-Square Cipher', 'https://awictor.github.io/four-square/'],
  ['Palindrome Checker', 'https://awictor.github.io/palindrome/'],
  ['Cap Rate', 'https://awictor.github.io/cap-rate/'],
  ['JsonKeyCase', 'https://awictor.github.io/json-keycase/'],
  ['AC BTU Calculator', 'https://awictor.github.io/btu-calc/'],
  ['Glasgow Coma Scale', 'https://awictor.github.io/gcs-calc/'],
  ['Two-Square Cipher', 'https://awictor.github.io/two-square/'],
  ['Homophone Checker', 'https://awictor.github.io/homophone-check/'],
  ['Loan-to-Value', 'https://awictor.github.io/ltv-calc/'],
  ['JsonToGraphQL', 'https://awictor.github.io/json-to-graphql/'],
  ['Rainwater Harvest', 'https://awictor.github.io/rain-barrel/'],
  ['APGAR Score', 'https://awictor.github.io/apgar-score/'],
  ['ADFGVX Cipher', 'https://awictor.github.io/adfgvx/'],
  ['Full-Width Text', 'https://awictor.github.io/fullwidth/'],
  ['Lease vs Buy', 'https://awictor.github.io/lease-vs-buy/'],
  ['JsonToCSharp', 'https://awictor.github.io/json-to-csharp/'],
  ['Fence Calculator', 'https://awictor.github.io/fence-calc/'],
  ['qSOFA', 'https://awictor.github.io/qsofa/'],
  ['Damm Check Digit', 'https://awictor.github.io/damm/'],
  ['Zalgo Text', 'https://awictor.github.io/zalgo/'],
  ['Small Caps Text', 'https://awictor.github.io/small-caps/'],
  ['Haversine', 'https://awictor.github.io/haversine/'],
  ['ISBN Tools', 'https://awictor.github.io/isbn/'],
  ['Depreciation Calculator', 'https://awictor.github.io/depreciation/'],
  ['JSON Patch', 'https://awictor.github.io/json-patch/'],
  ['Child-Pugh Score', 'https://awictor.github.io/child-pugh/'],
  ['Fuel Economy Converter', 'https://awictor.github.io/fuel-economy/'],
  ['EOQ Calculator', 'https://awictor.github.io/eoq-calc/'],
  ['Credit Card Validator', 'https://awictor.github.io/credit-card/'],
  ['Statistics Calculator', 'https://awictor.github.io/stats-calc/'],
  ['Scrabble Score', 'https://awictor.github.io/scrabble-score/'],
  ['Mean Arterial Pressure', 'https://awictor.github.io/mean-arterial-pressure/'],
  ['Pressure Converter', 'https://awictor.github.io/pressure-converter/'],
  ['Gray Code Converter', 'https://awictor.github.io/gray-code/'],
  ['Inventory Turnover', 'https://awictor.github.io/inventory-turnover/'],
  ['Remove Diacritics', 'https://awictor.github.io/remove-diacritics/'],
  ['Prime Factorization', 'https://awictor.github.io/prime-factorization/'],
  ['Waist-to-Hip Ratio', 'https://awictor.github.io/waist-hip-ratio/'],
  ['WACC Calculator', 'https://awictor.github.io/wacc-calc/'],
  ['Combinations &amp; Permutations', 'https://awictor.github.io/combinatorics/'],
  ['Collatz Conjecture', 'https://awictor.github.io/collatz/'],
  ['Speed Converter', 'https://awictor.github.io/speed-converter/'],
  ['Hamming Distance', 'https://awictor.github.io/hamming-distance/'],
  ['GCD &amp; LCM', 'https://awictor.github.io/gcd-lcm/'],
  ['Reading Time Estimator', 'https://awictor.github.io/reading-time/'],
  ['CAC &amp; LTV', 'https://awictor.github.io/cac-ltv/'],
  ['A-a Gradient', 'https://awictor.github.io/aa-gradient/'],
  ['Line Height Calculator', 'https://awictor.github.io/line-height-calc/'],
  ['Energy Converter', 'https://awictor.github.io/energy-converter/'],
  ['Churn &amp; Retention', 'https://awictor.github.io/churn-retention/'],
  ['Power Converter', 'https://awictor.github.io/power-converter/'],
  ['Force Converter', 'https://awictor.github.io/force-converter/'],
  ['Ordinal Numbers', 'https://awictor.github.io/ordinal-numbers/'],
  ['Adler-32 Checksum', 'https://awictor.github.io/adler32/'],
  ['Torque Converter', 'https://awictor.github.io/torque-converter/'],
  ['Frequency ↔ Wavelength', 'https://awictor.github.io/frequency-wavelength/'],
  ['Dice Roller', 'https://awictor.github.io/dice-roller/'],
  ['Quadratic Solver', 'https://awictor.github.io/quadratic-solver/'],
  ['Fibonacci Calculator', 'https://awictor.github.io/fibonacci/'],
  ['Digital Root', 'https://awictor.github.io/digital-root/'],
  ['Modular Exponentiation', 'https://awictor.github.io/modular-exponentiation/'],
  ['Sell-Through Rate', 'https://awictor.github.io/sell-through/'],
  ['Modular Inverse', 'https://awictor.github.io/modular-inverse/'],
  ['RBC Indices', 'https://awictor.github.io/rbc-indices/'],
  ['Armstrong Numbers', 'https://awictor.github.io/armstrong-number/'],
  ['BUN/Creatinine Ratio', 'https://awictor.github.io/bun-creatinine/'],
  ['Humidex', 'https://awictor.github.io/humidex/'],
  ['Cooking Converter', 'https://awictor.github.io/cooking-converter/'],
  ['Perfect Numbers', 'https://awictor.github.io/perfect-number/'],
  ['GMROI', 'https://awictor.github.io/gmroi-calc/'],
  ['Happy Numbers', 'https://awictor.github.io/happy-number/'],
  ['Contribution Margin', 'https://awictor.github.io/contribution-margin/'],
  ['Aspect Fit', 'https://awictor.github.io/aspect-fit/'],
  ['Catalan Numbers', 'https://awictor.github.io/catalan-number/'],
  ['Scale Converter', 'https://awictor.github.io/scale-converter/'],
  ["Amdahl's Law", 'https://awictor.github.io/amdahls-law/'],
  ['Kelly Criterion', 'https://awictor.github.io/kelly-criterion/'],
  ["Little's Law", 'https://awictor.github.io/littles-law/'],
  ['Sharpe Ratio', 'https://awictor.github.io/sharpe-ratio/'],
  ['ABV Calculator', 'https://awictor.github.io/abv-calc/'],
  ['Bloom Filter Calculator', 'https://awictor.github.io/bloom-filter/'],
  ['Black-Scholes Option Pricer', 'https://awictor.github.io/black-scholes/'],
  ['FFMI Calculator', 'https://awictor.github.io/ffmi-calc/'],
  ['Decibel Calculator', 'https://awictor.github.io/decibel-calc/'],
  ['Nyquist Sampling Calculator', 'https://awictor.github.io/nyquist-calc/'],
  ['Bearing Calculator', 'https://awictor.github.io/bearing-calc/'],
  ['Continued Fraction', 'https://awictor.github.io/continued-fraction/'],
  ['Day of the Week', 'https://awictor.github.io/day-of-week/'],
  ["Bayes' Theorem", 'https://awictor.github.io/bayes-theorem/'],
  ['Egyptian Fraction', 'https://awictor.github.io/egyptian-fraction/'],
  ["Euler's Totient", 'https://awictor.github.io/euler-totient/'],
  ['Linear Regression', 'https://awictor.github.io/linear-regression/'],
  ['Ideal Gas Law', 'https://awictor.github.io/ideal-gas-law/'],
  ['Projectile Motion', 'https://awictor.github.io/projectile-motion/'],
  ['Bond Yield Calculator', 'https://awictor.github.io/bond-yield/'],
  ['Chinese Remainder Theorem', 'https://awictor.github.io/chinese-remainder/'],
  ['Tap Code', 'https://awictor.github.io/tap-code/'],
  ['Half-Life Calculator', 'https://awictor.github.io/half-life/'],
  ['Gear Ratio Calculator', 'https://awictor.github.io/gear-ratio/'],
  ['Tower of Hanoi', 'https://awictor.github.io/tower-of-hanoi/'],
  ['CAPM Calculator', 'https://awictor.github.io/capm-calc/'],
  ['Descriptive Statistics', 'https://awictor.github.io/descriptive-statistics/'],
  ['Molarity &amp; Dilution', 'https://awictor.github.io/molarity-dilution/'],
  ['Voltage Divider', 'https://awictor.github.io/voltage-divider/'],
  ['Pendulum Period', 'https://awictor.github.io/pendulum-period/'],
  ['Divisor Sum', 'https://awictor.github.io/divisor-sum/'],
  ['Time Value of Money', 'https://awictor.github.io/time-value-of-money/'],
  ['Schwarzschild Radius', 'https://awictor.github.io/schwarzschild-radius/'],
  ['Beer-Lambert Law', 'https://awictor.github.io/beer-lambert/'],
  ['Duty Cycle / PWM', 'https://awictor.github.io/duty-cycle/'],
  ['A1Z26 Cipher', 'https://awictor.github.io/a1z26/'],
  ['Matrix Calculator', 'https://awictor.github.io/matrix-calculator/'],
  ['Exposure Value', 'https://awictor.github.io/exposure-value/'],
  ["Snell's Law", 'https://awictor.github.io/snells-law/'],
  ['Reynolds Number', 'https://awictor.github.io/reynolds-number/'],
  ['Grade &amp; Slope', 'https://awictor.github.io/grade-slope/'],
  ['Sieve of Eratosthenes', 'https://awictor.github.io/sieve-of-eratosthenes/'],
  ['Speed of Sound', 'https://awictor.github.io/speed-of-sound/'],
  ['Rule of 78', 'https://awictor.github.io/rule-of-78/'],
  ['Escape Velocity', 'https://awictor.github.io/escape-velocity/'],
  ['Kinetic Energy &amp; Momentum', 'https://awictor.github.io/kinetic-energy/'],
  ['Complex Number Calculator', 'https://awictor.github.io/complex-number/'],
  ['Vector Calculator', 'https://awictor.github.io/vector-calculator/'],
  ['Board Feet', 'https://awictor.github.io/board-feet/'],
  ['Quaternion Calculator', 'https://awictor.github.io/quaternion/'],
  ['Photon Energy', 'https://awictor.github.io/photon-energy/'],
  ['Doppler Effect', 'https://awictor.github.io/doppler-effect/'],
  ['de Broglie Wavelength', 'https://awictor.github.io/de-broglie/'],
  ['Coordinate Converter', 'https://awictor.github.io/coord-convert/'],
  ['Field of View', 'https://awictor.github.io/focal-length/'],
  ['Hyperfocal Distance', 'https://awictor.github.io/hyperfocal/'],
  ['Truth Table Generator', 'https://awictor.github.io/truth-table/'],
  ['Betting Odds Converter', 'https://awictor.github.io/betting-odds/'],
  ['RC / LC Filter', 'https://awictor.github.io/rc-filter/'],
  ['Centripetal Force', 'https://awictor.github.io/centripetal/'],
  ["Hooke's Law", 'https://awictor.github.io/spring-constant/'],
  ['pH Calculator', 'https://awictor.github.io/ph-calc/'],
  ['Proportion Solver', 'https://awictor.github.io/proportion-solver/'],
  ['robots.txt Generator', 'https://awictor.github.io/robots-txt/'],
  ['CORS Header Generator', 'https://awictor.github.io/cors-generator/'],
  ['Sitemap.xml Generator', 'https://awictor.github.io/sitemap-generator/'],
  ['Expression Calculator', 'https://awictor.github.io/expression-calculator/'],
  ['Julian Day Converter', 'https://awictor.github.io/julian-day/'],
  ['Weighted Average', 'https://awictor.github.io/weighted-average/'],
  ['Modulo Calculator', 'https://awictor.github.io/modulo-calc/'],
  ['Leap Year Checker', 'https://awictor.github.io/leap-year/'],
  ['.editorconfig Generator', 'https://awictor.github.io/editorconfig/'],
  ['Numerical Integrator', 'https://awictor.github.io/numerical-integration/'],
  ['Derivative Calculator', 'https://awictor.github.io/derivative-calculator/'],
  ['Root Finder', 'https://awictor.github.io/root-finder/'],
  ['Lerp &amp; Remap', 'https://awictor.github.io/lerp/'],
  ['Function Grapher', 'https://awictor.github.io/function-grapher/'],
  ['Normal Distribution', 'https://awictor.github.io/normal-distribution/'],
  ['Binomial Probability', 'https://awictor.github.io/binomial-probability/'],
  ['Poisson Distribution', 'https://awictor.github.io/poisson/'],
  ['Repeating Decimal', 'https://awictor.github.io/repeating-decimal/'],
  ['RPN Calculator', 'https://awictor.github.io/rpn-calculator/'],
  ['Specific Heat', 'https://awictor.github.io/specific-heat/'],
  ['Thermal Expansion', 'https://awictor.github.io/thermal-expansion/'],
  ['Terminal Velocity', 'https://awictor.github.io/terminal-velocity/'],
  ['LED Resistor', 'https://awictor.github.io/led-resistor/'],
  ['Linear System Solver', 'https://awictor.github.io/linear-system/'],
  ['Meeting Cost', 'https://awictor.github.io/meeting-cost/'],
  ['Roast Cooking Time', 'https://awictor.github.io/roast-time/'],
  ['Wire Gauge (AWG)', 'https://awictor.github.io/awg-calc/'],
  ['Tank Volume', 'https://awictor.github.io/tank-volume/'],
  ['Gravitational Force', 'https://awictor.github.io/gravitational-force/'],
  ['Thin Lens Equation', 'https://awictor.github.io/thin-lens/'],
  ['Density Calculator', 'https://awictor.github.io/density-calc/'],
  ['Work, Energy &amp; Power', 'https://awictor.github.io/work-energy/'],
  ['Pressure Calculator', 'https://awictor.github.io/pressure-calc/'],
  ['Polynomial Calculator', 'https://awictor.github.io/polynomial/'],
  ['Sample Size Calculator', 'https://awictor.github.io/sample-size/'],
  ['Confidence Interval', 'https://awictor.github.io/confidence-interval/'],
  ['Pythagorean Means', 'https://awictor.github.io/pythagorean-means/'],
  ['Timecode Calculator', 'https://awictor.github.io/timecode-calc/'],
  ['Bitrate Calculator', 'https://awictor.github.io/bitrate-calc/'],
  ['Engine Displacement', 'https://awictor.github.io/engine-displacement/'],
  ['Compression Ratio', 'https://awictor.github.io/compression-ratio/'],
  ['Horsepower Calculator', 'https://awictor.github.io/horsepower-calc/'],
  ['Pool Volume Calculator', 'https://awictor.github.io/pool-volume/'],
  ['Pulley &amp; Belt Calculator', 'https://awictor.github.io/pulley-belt/'],
  ['ADA Ramp Calculator', 'https://awictor.github.io/ada-ramp/'],
  ['Drywall Calculator', 'https://awictor.github.io/drywall-calc/'],
  ['Beam Deflection', 'https://awictor.github.io/beam-deflection/'],
  ['555 Timer Calculator', 'https://awictor.github.io/ne555-timer/'],
  ['Battery Life Calculator', 'https://awictor.github.io/battery-life/'],
  ['Dipole Antenna Calculator', 'https://awictor.github.io/dipole-antenna/'],
  ['LM317 Calculator', 'https://awictor.github.io/lm317-calc/'],
  ['Op-Amp Gain Calculator', 'https://awictor.github.io/opamp-gain/'],
  ['Coil Inductance Calculator', 'https://awictor.github.io/coil-inductance/'],
  ['Voltage Drop Calculator', 'https://awictor.github.io/voltage-drop/'],
  ['Telescope Calculator', 'https://awictor.github.io/telescope-calc/'],
  ['Muzzle Energy Calculator', 'https://awictor.github.io/muzzle-energy/'],
  ['Golf Handicap Calculator', 'https://awictor.github.io/golf-handicap/'],
  ['Elo Rating Calculator', 'https://awictor.github.io/elo-rating/'],
  ['Poker Pot Odds', 'https://awictor.github.io/pot-odds/'],
  ['Bowling Score Calculator', 'https://awictor.github.io/bowling-score/'],
  ['Crosswind Calculator', 'https://awictor.github.io/crosswind-calc/'],
  ['Density Altitude Calculator', 'https://awictor.github.io/density-altitude/'],
  ['Cloud Base Calculator', 'https://awictor.github.io/cloud-base/'],
  ['Solar Panel Calculator', 'https://awictor.github.io/solar-panel/'],
  ['Electricity Cost Calculator', 'https://awictor.github.io/electricity-cost/'],
  ['Plant Spacing Calculator', 'https://awictor.github.io/plant-spacing/'],
  ['CO2 Emissions Calculator', 'https://awictor.github.io/co2-emissions/'],
  ['3D Print Cost Calculator', 'https://awictor.github.io/print-cost/'],
  ['IBU Calculator', 'https://awictor.github.io/ibu-calc/'],
  ['Rowing Split Calculator', 'https://awictor.github.io/rowing-split/'],
  ['Watts per Kilogram', 'https://awictor.github.io/watts-per-kg/'],
  ['Dog Age Calculator', 'https://awictor.github.io/dog-age/'],
  ['Bike Gearing Calculator', 'https://awictor.github.io/gear-inches/'],
  ['Caffeine Calculator', 'https://awictor.github.io/caffeine-calc/'],
  ['Swim Pace Calculator', 'https://awictor.github.io/swim-pace/'],
  ['Speedometer Error', 'https://awictor.github.io/speedometer-error/'],
  ['Sound Level &amp; Distance', 'https://awictor.github.io/sound-distance/'],
  ['Fuel Range Calculator', 'https://awictor.github.io/fuel-range/'],
  ['Reverb Time (RT60)', 'https://awictor.github.io/reverb-time/'],
  ['Tire Pressure &amp; Temperature', 'https://awictor.github.io/tire-pressure/'],
  ['Brine Calculator', 'https://awictor.github.io/brine-calc/'],
  ['Typing Speed Calculator', 'https://awictor.github.io/typing-speed/'],
  ['Yeast Converter', 'https://awictor.github.io/yeast-converter/'],
  ['Party Servings Calculator', 'https://awictor.github.io/servings-calc/'],
  ['DPI / Print Size Calculator', 'https://awictor.github.io/dpi-calc/'],
  ['Ring Size Converter', 'https://awictor.github.io/ring-size/'],
  ['Two-Stroke Fuel Mix', 'https://awictor.github.io/two-stroke/'],
  ['Dilution Ratio Calculator', 'https://awictor.github.io/dilution-ratio/'],
  ['Epoxy / Resin Mix', 'https://awictor.github.io/epoxy-ratio/'],
  ['EV Charging Time', 'https://awictor.github.io/ev-charging/'],
  ['Gravel Calculator', 'https://awictor.github.io/gravel-calc/'],
  ['Snow Load Calculator', 'https://awictor.github.io/snow-load/'],
  ['RAID Calculator', 'https://awictor.github.io/raid-calc/'],
  ['Cash-on-Cash Return', 'https://awictor.github.io/cash-on-cash/'],
  ['Transformer Calculator', 'https://awictor.github.io/transformer-calc/'],
  ['Reorder Point &amp; Safety Stock', 'https://awictor.github.io/reorder-point/'],
  ['Time Value of Money', 'https://awictor.github.io/tvm-calc/'],
  ['Growing Degree Days', 'https://awictor.github.io/gdd-calc/'],
  ['Resistor Network Calculator', 'https://awictor.github.io/resistor-network/'],
  ['Molar Mass Calculator', 'https://awictor.github.io/molar-mass/'],
  ['Orbital Period Calculator', 'https://awictor.github.io/orbital-period/'],
  ['Wet-Bulb Temperature', 'https://awictor.github.io/wet-bulb/'],
  ['String Tension &amp; Frequency', 'https://awictor.github.io/string-tension/'],
  ['Cat Age Calculator', 'https://awictor.github.io/cat-age/'],
  ['Rental Yield Calculator', 'https://awictor.github.io/rental-yield/'],
  ['Freelance Rate Calculator', 'https://awictor.github.io/freelance-rate/'],
  ['Net Worth Calculator', 'https://awictor.github.io/net-worth/'],
  ['Buoyancy Calculator', 'https://awictor.github.io/buoyancy/'],
  ['Pipe Flow Rate Calculator', 'https://awictor.github.io/pipe-flow/'],
  ['Capacitor Network Calculator', 'https://awictor.github.io/capacitor-network/'],
  ['Shutter Angle Calculator', 'https://awictor.github.io/shutter-angle/'],
  ['Hat Size Calculator', 'https://awictor.github.io/hat-size/'],
  ['VSWR Calculator', 'https://awictor.github.io/vswr-calc/'],
  ['Watt-Hour &amp; Battery Pack', 'https://awictor.github.io/watt-hours/'],
  ['Air Changes per Hour', 'https://awictor.github.io/air-changes/'],
  ['TV Size &amp; Viewing Distance', 'https://awictor.github.io/viewing-distance/'],
  ['Crop Factor &amp; Equivalent Focal Length', 'https://awictor.github.io/crop-factor/'],
  ['Balance Transfer Calculator', 'https://awictor.github.io/balance-transfer/'],
  ['Rebar Calculator', 'https://awictor.github.io/rebar-calc/'],
  ['Flooring Calculator', 'https://awictor.github.io/flooring-calc/'],
  ['Lottery Odds Calculator', 'https://awictor.github.io/lottery-odds/'],
  ['PTO Accrual Calculator', 'https://awictor.github.io/pto-accrual/'],
  ['Boiling Point at Altitude', 'https://awictor.github.io/boiling-point/'],
  ['Generator Sizing Calculator', 'https://awictor.github.io/generator-sizing/'],
  ['Standard Drinks Calculator', 'https://awictor.github.io/standard-drinks/'],
  ['Keg Calculator', 'https://awictor.github.io/keg-calc/'],
  ['Bolt Torque Calculator', 'https://awictor.github.io/bolt-torque/'],
  ['Pool Chlorine Calculator', 'https://awictor.github.io/pool-chlorine/'],
  ['Brix Calculator', 'https://awictor.github.io/brix-calc/'],
  ['Water Hardness Converter', 'https://awictor.github.io/water-hardness/'],
  ['Cricket Chirp Thermometer', 'https://awictor.github.io/cricket-thermometer/'],
  ['Tap Drill Size Calculator', 'https://awictor.github.io/tap-drill/'],
  ['LED Strip Power Calculator', 'https://awictor.github.io/led-strip/'],
  ['EV vs Gas Cost Calculator', 'https://awictor.github.io/ev-savings/'],
  ['Machining Speeds &amp; Feeds', 'https://awictor.github.io/speeds-feeds/'],
  ['Absolute Humidity Calculator', 'https://awictor.github.io/absolute-humidity/'],
  ['Superheat &amp; Subcooling Calculator', 'https://awictor.github.io/superheat/'],
  ['Coffee Extraction Calculator', 'https://awictor.github.io/coffee-extraction/'],
  ['eDPI &amp; Sensitivity Converter', 'https://awictor.github.io/mouse-sensitivity/'],
  ['Vertical Jump Calculator', 'https://awictor.github.io/vertical-jump/'],
  ['Steps to Distance Calculator', 'https://awictor.github.io/steps-distance/'],
  ['LLM Token Cost Calculator', 'https://awictor.github.io/token-cost/'],
  ['LLM VRAM Calculator', 'https://awictor.github.io/llm-vram/'],
  ['Uptime SLA Calculator', 'https://awictor.github.io/uptime-sla/'],
  ['OEE Calculator', 'https://awictor.github.io/oee-calc/'],
  ['Takt Time Calculator', 'https://awictor.github.io/takt-time/'],
  ['Per Diem Calculator', 'https://awictor.github.io/per-diem/'],
  ['Dehumidifier Sizing', 'https://awictor.github.io/dehumidifier/'],
  ['Compost C:N Ratio', 'https://awictor.github.io/compost-ratio/'],
  ['Wind Turbine Power', 'https://awictor.github.io/wind-turbine/'],
  ['Propane Tank Runtime', 'https://awictor.github.io/propane-runtime/'],
  ['Sealed Speaker Box', 'https://awictor.github.io/speaker-box/'],
  ['Spoke Length', 'https://awictor.github.io/spoke-length/'],
  ['Room Modes', 'https://awictor.github.io/room-modes/'],
  ['Hull Speed', 'https://awictor.github.io/hull-speed/'],
  ['Tongue Weight', 'https://awictor.github.io/tongue-weight/'],
  ['Anchor Scope', 'https://awictor.github.io/anchor-scope/'],
  ['Sail Area Ratio', 'https://awictor.github.io/sail-area/'],
  ['Fabric Yardage', 'https://awictor.github.io/fabric-yardage/'],
  ['Star Exposure', 'https://awictor.github.io/500-rule/'],
  ['Timelapse', 'https://awictor.github.io/timelapse/'],
  ['Arrow Kinetic Energy', 'https://awictor.github.io/arrow-ke/'],
  ['Flash Guide Number', 'https://awictor.github.io/flash-guide-number/'],
  ["Baker's Percentage", 'https://awictor.github.io/bakers-percentage/'],
  ['Cold Brew Ratio', 'https://awictor.github.io/cold-brew/'],
  ['Grass Seed', 'https://awictor.github.io/grass-seed/'],
  ['Fertilizer Rate', 'https://awictor.github.io/fertilizer-rate/'],
  ['Ceiling Fan Size', 'https://awictor.github.io/ceiling-fan/'],
  ['Take-Home Pay', 'https://awictor.github.io/take-home/'],
  ['JsonToSwift', 'https://awictor.github.io/json-to-swift/'],
  ['Deck Board Calculator', 'https://awictor.github.io/deck-calc/'],
  ['HAS-BLED', 'https://awictor.github.io/has-bled/'],
  ['Base45', 'https://awictor.github.io/base45/'],
  ['Bcrypt Inspector', 'https://awictor.github.io/bcrypt-inspector/'],
  ['Inclusive Language', 'https://awictor.github.io/inclusive-language/'],
  ['Emergency Fund', 'https://awictor.github.io/emergency-fund/'],
  ['CRC Calculator', 'https://awictor.github.io/crc-calc/'],
  ['Aquarium Volume', 'https://awictor.github.io/aquarium-volume/'],
  ['Opioid MME', 'https://awictor.github.io/opioid-mme/'],
];

let n = 0; const check = (name, fn) => { fn(); n++; console.log('  ok -', name); };

for (const [name, url] of tools) {
  check(`links ${name}`, () => {
    assert.ok(html.includes(url), `missing URL ${url}`);
    assert.ok(html.includes('>' + name + '<'), `missing name ${name}`);
  });
}
check('exactly 684 tool cards', () => {
  assert.equal((html.match(/class="card"/g) || []).length, 684);
});
check('tools grouped into category sections', () => {
  assert.equal((html.match(/class="cat"/g) || []).length, 7);
  for (const c of ['Finance', 'Developer', 'Design', 'Security', 'Writing', 'Health', 'Everyday'])
    assert.ok(html.includes('<h3>' + c) || html.includes(c + '</h3>') || new RegExp('<h3>'+c).test(html), 'missing category ' + c);
});
check('valid JSON-LD ItemList with 684 items', () => {
  const m = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
  assert.ok(m, 'no JSON-LD block');
  const data = JSON.parse(m[1]);
  assert.equal(data['@type'], 'ItemList');
  assert.equal(data.itemListElement.length, 684);
  assert.equal(data.itemListElement[0].item.url, tools[0][1]);
});

check('sitemap.xml lists all 684 pages', () => {
  const sm = readFileSync(join(__dirname, '..', 'sitemap.xml'), 'utf8');
  const urls = ['toolkit', ...tools.map(t => t[1])];
  assert.equal((sm.match(/<loc>/g) || []).length, 685);
  assert.ok(sm.includes('https://awictor.github.io/toolkit/'));
  for (const [, url] of tools) assert.ok(sm.includes(url), 'sitemap missing ' + url);
});

// Evaluate the hub script in a minimal DOM stub to exercise the pure filter.
function el(){ return {value:'',textContent:'',style:{},className:'',getAttribute(){return null;},setAttribute(){},addEventListener(){},querySelectorAll(){return[];},onclick:null}; }
globalThis.document={getElementById:()=>el(),querySelectorAll:()=>[],documentElement:el()};
globalThis.localStorage={getItem:()=>null,setItem(){},removeItem(){}};
globalThis.window={matchMedia:()=>({matches:false})};
globalThis.matchMedia=globalThis.window.matchMedia;
const js=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).sort((a,b)=>b.length-a.length)[0];
eval(js+`\n;globalThis.__t={filterTools};`);
const filterTools=globalThis.__t.filterTools;

check('filterTools: matches name or description, case-insensitive', () => {
  const items=[{name:'MarginMaster',desc:'Amazon FBA true-profit'},{name:'Payoff',desc:'debt snowball'},{name:'NestEgg',desc:'compound interest'}];
  assert.equal(filterTools(items,'').length, 3);
  assert.deepEqual(filterTools(items,'debt').map(i=>i.name), ['Payoff']);
  assert.deepEqual(filterTools(items,'AMAZON').map(i=>i.name), ['MarginMaster']);
  assert.deepEqual(filterTools(items,'interest').map(i=>i.name), ['NestEgg']);
  assert.equal(filterTools(items,'zzz').length, 0);
  assert.equal(filterTools(items,'   ').length, 3); // whitespace-only = no filter
});
check('filterTools: supports a combined text field', () => {
  const items=[{text:'Runway SaaS metrics'},{text:'RateRight freelance'}];
  assert.deepEqual(filterTools(items,'saas'), [items[0]]);
});

console.log(`\n${n} checks passed.`);
